server:
    port: 8084
spring:
    application:
      name: gateway
    cloud:
        gateway:
            routes:
                - id: account
                  uri: lb://account
                  predicates:
                  - Path=/account/**
                - id: transaction
                  uri: lb://transaction
                  predicates:
                    - Path=/transaction/**
                - id: patients
                  uri: lb://patients
                  predicates:
                    - Path=/patients/**
                - id: doctors
                  uri: lb://doctors
                  predicates:
                    - Path=/doctors/**
                - id: appointment
                  uri: lb://appointment
                  predicates:
                    - Path=/appointments/**

eureka:
    client:
        service-url:
            defaultZone: http://discovery:8761/eureka/